[tox]
envlist =
    py3.14, py3.13

skip_missing_interpreters = True
isolated_build = True
labels =
    update = update
    prep-release = prep-release

[testenv]
allowlist_externals =
    echo
skip_install = true
commands =
    echo "test!"


[testenv:update]
base_python = py3.9
skip_install = true
commands =
    python -VV
    python writer.py


[testenv:prep-release]
# `prep-release` is used in CI by the `_prep-release` workflow.
description = Make the changes needed to create a new release PR
deps =
    poetry
    scriv
pass_env =
    VERSION
    PR_BODY_OUTPUT_PATH
commands =
    # Fail if $VERSION is not set.
    python -Ec 'import os; assert (v := os.getenv("VERSION")) is not None, v'
    poetry version "{env:VERSION}"
    scriv print --version "{env:VERSION}" --output "{env:PR_BODY_OUTPUT_PATH:{env:VERSION}.rst}"
