# This file is a part of Kurt McKee's GitHub Workflows project.
# https://github.com/kurtmckee/github-workflows
# Copyright 2024-2026 Kurt McKee <contactme@kurtmckee.org>
# SPDX-License-Identifier: MIT

import pathlib
import sys
import tomllib
import typing

import jinja2

ROOT = pathlib.Path(__file__).parent.parent
WORKFLOWS = ROOT / ".github/workflows/"


def main() -> int:
    files_changed = False

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(WORKFLOWS),
        keep_trailing_newline=True,
        # The default Jinja variable syntax, "{{ ... }}",
        # conflicts with the GitHub workflow syntax "${{ ... }}".
        # To avoid conflict, braces in Jinja syntax are converted to braces.
        block_start_string="[%",
        block_end_string="%]",
        variable_start_string="[[",
        variable_end_string="]]",
        comment_start_string="#[#",
        comment_end_string="#]#",
    )
    for template_path in WORKFLOWS.glob("*.jinja.yaml"):
        target = template_path.name[: -len(".jinja.yaml")]
        include_file = create_file_includer(target)
        template = env.get_template(template_path.name)
        new_content = f"# DO NOT EDIT THIS FILE! EDIT '{template_path.name}'.\n\n"
        new_content += template.render(
            PYTHON_VERSION=get_python_version(),
            UV_VERSION=get_uv_version(),
            include_requirements=include_requirements,
            include_file=include_file,
        )

        path = WORKFLOWS / f"{target}.yaml"
        content = path.read_text()
        if new_content != content:
            path.write_text(new_content)
            files_changed = True

    return int(files_changed)


def create_file_includer(name: str) -> typing.Callable[[str], str]:
    name = name.replace("-", "_")
    path = ROOT / f"src/workflow_assets/{name}"

    def include_file(file: str) -> str:
        return (path / file).read_text().rstrip()

    return include_file


def include_requirements(name: str) -> str:
    name = name.replace("-", "_")
    path = ROOT / f"requirements/{name}/requirements.txt"
    if not path.is_file():
        raise SystemExit(f"{path} does not exist")
    return path.read_text().rstrip()


def get_python_version() -> str:
    config = tomllib.loads((ROOT / "pyproject.toml").read_text())
    specifier = str(config["project"]["requires-python"])
    version = next(
        piece.strip("<>=")
        for piece in specifier.partition(",")
        if piece.startswith(">=")
    )
    return version.strip()


def get_uv_version() -> str:
    text = (ROOT / "requirements/uv/requirements.txt").read_text()
    line = next(line_ for line_ in text.splitlines() if line_.startswith("uv"))
    specifier, _, _ = line.partition(";")
    _, _, version = specifier.partition("==")
    return version.strip()


if __name__ == "__main__":
    sys.exit(main())
